# If the agent runs on a different machine, replace localhost with the server's IP address
# in both nats.url and agent.serverurl. Example: 192.168.1.10
env = "prod"

[server]
port     = 4040
altport  = 8080
webdir   = "web/public"

[nats]
url = "nats://localhost:4222"

[postgres]
host     = "localhost"
port     = 5432
user     = "ebpf_user"
password = "ebpf_secret_password"
db       = "policy_metrics"

[agent]
interface  = "enp0s5"
agentid    = "agent-ahmad"
serverurl  = "http://localhost:8080"
topic      = "production"  # leave empty for all topics
