env = "production"

[server]
port     = 4040
web_dir  = "web/public"

[nats]
url = "nats://localhost:4222"

[agent]
interface  = "enp0s5"
agent_id   = "agent-ahmad"
server_url = "http://localhost:8080"
