// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type PolicyIpStats struct {
	_        structs.HostLayout
	Count    uint64
	LastSeen uint64
}

// LoadPolicy returns the embedded CollectionSpec for Policy.
func LoadPolicy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PolicyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Policy: %w", err)
	}

	return spec, err
}

// LoadPolicyObjects loads Policy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PolicyObjects
//	*PolicyPrograms
//	*PolicyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPolicyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPolicy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PolicySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PolicySpecs struct {
	PolicyProgramSpecs
	PolicyMapSpecs
	PolicyVariableSpecs
}

// PolicyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PolicyProgramSpecs struct {
	PolicyFilter *ebpf.ProgramSpec `ebpf:"policy_filter"`
}

// PolicyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PolicyMapSpecs struct {
	BlockList    *ebpf.MapSpec `ebpf:"block_list"`
	RequestCount *ebpf.MapSpec `ebpf:"request_count"`
}

// PolicyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PolicyVariableSpecs struct {
}

// PolicyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type PolicyObjects struct {
	PolicyPrograms
	PolicyMaps
	PolicyVariables
}

func (o *PolicyObjects) Close() error {
	return _PolicyClose(
		&o.PolicyPrograms,
		&o.PolicyMaps,
	)
}

// PolicyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type PolicyMaps struct {
	BlockList    *ebpf.Map `ebpf:"block_list"`
	RequestCount *ebpf.Map `ebpf:"request_count"`
}

func (m *PolicyMaps) Close() error {
	return _PolicyClose(
		m.BlockList,
		m.RequestCount,
	)
}

// PolicyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadPolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type PolicyVariables struct {
}

// PolicyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type PolicyPrograms struct {
	PolicyFilter *ebpf.Program `ebpf:"policy_filter"`
}

func (p *PolicyPrograms) Close() error {
	return _PolicyClose(
		p.PolicyFilter,
	)
}

func _PolicyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed policy_bpfeb.o
var _PolicyBytes []byte
